### ISSUE TITLE
While upgrading cakephp1.3 to php7.1, session_start is not working

### ISSUE THREAD

**Issue by rozyaarav** [littleant/cakephp-1.3.21#11]
When i am trying to login with my application, i found this issue:-
**Warning (2): session_start() [function.session-start]: Failed to read session data: user (path: /var/lib/php/sessions) [CORE/cake/libs/cake_session.php, line 588]** in **"https://github.com/littleant/cakephp-1.3.21"**

**Comment by littleant** [comment]
This should now be fixed.
