### ISSUE TITLE
Redirect is not working

### ISSUE THREAD

**Issue by MGCavijit** [littleant/cakephp-1.3.21#16]
$this->redirect(array('controller'=>'logins','action'=>'index'), null, true);

**Comment by MGCavijit** [comment]
I see Router::url($url, true)) this function is not working.

**Comment by cebcardoso** [comment]
Also ran into this issue. Here is what I did to resolve it:

1. Made the url() method non static
2. Changed `if (isset($self) && !isset($self->params['requested'])) {` to `if (isset($this) && !isset($this->params['requested'])) {`

Hope it helps.

**Comment by littleant** [comment]
I reverted the changes to the original, non-static version of this method.
Now static-usage will produce a Notice again, but at least it should now work like before.
