### ISSUE TITLE
Undefined index: HTTP_USER_AGENT in cake_session when running in CLI mode

### ISSUE THREAD

**Issue by rkuntoro** [littleant/cakephp-1.3.21#17]
Getting a PHP notice when running the app on CLI:

`Notice: Undefined index: HTTP_USER_AGENT in /var/www/app/cake/libs/cake_session.php on line 504`

It's caused by this line:

`$shouldSendSameSiteNone = SameSite::handle($_SERVER['HTTP_USER_AGENT']);`

Not sure what the appropriate fix is, we currently add `php_sapi_name() != 'cli'` into the if statement.

Edit: Alternatively use cake's `env('HTTP_USER_AGENT')` instead of `$_SERVER['HTTP_USER_AGENT']`

**Comment by littleant** [comment]
Thanks for opening this issue @rkuntoro!

I would merge a pull request for a solution with `env('HTTP_USER_AGENT')` if you want to provide one.
