### ISSUE TITLE
Uncaught Error: Call to undefined method DboSource::connect()

### ISSUE THREAD

**Issue by luxor99** [littleant/cakephp-1.3.21#27]
Hello, I followed the directions to allow my cakephp installation to run in PHP 8.0 but am gettng this error:

Fatal error: Uncaught Error: Call to undefined method DboSource::connect() in .../cake/libs/model/datasources/dbo_source.php:143

What could be the issue.  Here is my database.php config file:

class DATABASE_CONFIG {

    var $default = array(
       // 'driver' => 'mysql',
        'persistent' => false,
        'host' => xxx',
        'login' => 'xxx',
        'password' => 'xx',
        'database' => 'xx',
        'prefix'  => '',
    );
}

**Comment by n8man** [comment]
@luxor99 it looks like you need to set your driver to 'mysqli'

**Comment by littleant** [comment]
Closing this, because this should be solved.
