### ISSUE TITLE
Unable to configure the session, setting session.save_handler failed

### ISSUE THREAD

**Issue by akiyan** [littleant/cakephp-1.3.21#5]
in Configure::write('Session.save', 'database'); or Configure::write('Session.save', 'cache');

Recoverable fatal error: ini_set() [function.ini-set]: Cannot set 'user' save handler by ini_set() or session_module_name() in /home/akiyan/example/cake/libs/cake_session.php on line 512

**Comment by littleant** [comment]
This should be fixed now.
